# Generated by Django 5.2 on 2025-05-24 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.menteeprofile')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.mentorprofile')),
            ],
            options={
                'unique_together': {('mentee', 'mentor')},
            },
        ),
    ]
