# Generated by Django 5.2 on 2025-06-04 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchrequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='MeetingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('scheduled_time', models.DateTimeField()),
                ('meetining_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='matchrequest.matchrequest')),
            ],
        ),
    ]
