# Generated by Django 5.2 on 2025-06-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchrequest', '0002_alter_matchrequest_status_meetingschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingschedule',
            old_name='comment',
            new_name='weekly_goals',
        ),
        migrations.AddField(
            model_name='meetingschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
