# Generated by Django 5.2 on 2025-06-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchrequest', '0003_rename_comment_meetingschedule_weekly_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
