# Generated by Django 5.2 on 2025-06-13 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchrequest', '0004_matchrequest_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingschedule',
            old_name='weekly_goals',
            new_name='purpose',
        ),
    ]
