# Generated by Django 5.2 on 2025-05-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menteeprofile',
            old_name='experience',
            new_name='experience_years',
        ),
        migrations.RenameField(
            model_name='mentorprofile',
            old_name='experience',
            new_name='experience_years',
        ),
        migrations.RemoveField(
            model_name='menteeprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='menteeprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='expertise',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='expertise',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
