# Generated by Django 5.2 on 2025-06-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_experience_menteeprofile_experience_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteeprofile',
            name='passport_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='passport_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
