# Generated by Django 5.2 on 2025-06-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_menteeprofile_passport_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteeprofile',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
