# Generated by Django 5.2 on 2025-06-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_menteeprofile_username_mentorprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteeprofile',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Is the mentee currently available for mentorship?'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Is the mentor currently available for mentorship?'),
        ),
    ]
