# Generated by Django 5.2 on 2025-06-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_menteeprofile_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteeprofile',
            name='google_credentials',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='google_credentials',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
