# Generated by Django 5.2 on 2025-06-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_menteeprofile_address_menteeprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteeprofile',
            name='experience_years',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='experience_years',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
