# Generated by Django 5.2 on 2025-05-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_x_account_user_bio_user_company_user_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passport_image',
            field=models.ImageField(blank=True, null=True, upload_to='passport_images/'),
        ),
    ]
