# Generated by Django 5.2 on 2025-05-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_passport_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expertise',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
