# Generated by Django 5.2 on 2025-04-19 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_goal_completed_goal_created_by_goal_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorship',
            old_name='end_date',
            new_name='finish_date',
        ),
        migrations.CreateModel(
            name='Weeklycheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_id', models.PositiveIntegerField()),
                ('progress', models.TextField(blank=True, null=True)),
                ('challenges', models.TextField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('loop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='users.mentorship')),
            ],
            options={
                'unique_together': {('loop', 'week_id', 'created_by')},
            },
        ),
    ]
