# Generated by Django 5.2 on 2025-06-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_expertise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='experience',
            new_name='experience_years',
        ),
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Is the mentor currently available for mentorship?'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
