# Generated by Django 5.2 on 2025-04-30 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_interests_alter_profile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorship',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_loops', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_loops', to='users.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='mentorship',
            unique_together={('mentor', 'mentee')},
        ),
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('responded', models.BooleanField(default=False)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_requests', to='users.profile')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_requests', to='users.profile')),
            ],
            options={
                'unique_together': {('mentor', 'mentee')},
            },
        ),
    ]
