# Generated by Django 5.2 on 2025-05-24 10:28

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipLoop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=datetime.datetime(2025, 6, 21, 10, 27, 59, 260245, tzinfo=datetime.timezone.utc))),
                ('is_active', models.BooleanField(default=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.menteeprofile')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.mentorprofile')),
            ],
        ),
    ]
