# Generated by Django 5.2 on 2025-05-24 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshiploop',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 21, 10, 30, 10, 528857, tzinfo=datetime.timezone.utc)),
        ),
    ]
