# Generated by Django 5.2 on 2025-05-24 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_alter_mentorshiploop_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshiploop',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 21, 10, 31, 45, 490544, tzinfo=datetime.timezone.utc)),
        ),
    ]
