# Generated by Django 5.2 on 2025-05-26 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0003_alter_mentorshiploop_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshiploop',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 23, 16, 41, 22, 459449, tzinfo=datetime.timezone.utc)),
        ),
    ]
