# Generated by Django 5.2 on 2025-05-28 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0004_alter_mentorshiploop_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshiploop',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 25, 16, 34, 7, 875133, tzinfo=datetime.timezone.utc)),
        ),
    ]
