# Generated by Django 5.2 on 2025-06-04 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0005_alter_mentorshiploop_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshiploop',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 7, 2, 12, 29, 58, 594108, tzinfo=datetime.timezone.utc)),
        ),
    ]
