# Generated by Django 5.2 on 2025-06-05 17:35

import datetime
import mentorship.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0006_alter_mentorshiploop_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshiploop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 5, 17, 35, 27, 382628, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorshiploop',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mentorshiploop',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='mentorshiploop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mentorshiploop',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorshiploop',
            name='start_date',
            field=models.DateField(default=mentorship.models.default_start_date),
        ),
    ]
