# Generated by Django 5.2 on 2025-05-24 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentorship', '0002_alter_mentorshiploop_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('mentor_checked_in', models.BooleanField(default=False)),
                ('mentee_checked_in', models.BooleanField(default=False)),
                ('progress', models.TextField(blank=True, null=True)),
                ('challenges', models.TextField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('checkin_date', models.DateField(auto_now_add=True)),
                ('loop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship.mentorshiploop')),
            ],
            options={
                'unique_together': {('loop', 'week_number', 'checkin_date')},
            },
        ),
    ]
