# Generated by Django 5.2 on 2025-06-07 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0007_mentorshiploop_created_at_mentorshiploop_purpose_and_more'),
        ('weeklycheckin', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklycheckin',
            unique_together={('loop', 'week_number')},
        ),
        migrations.AddField(
            model_name='weeklycheckin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 7, 17, 26, 56, 634763, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklycheckin',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='weeklycheckin',
            name='checkin_date',
            field=models.DateField(),
        ),
    ]
