# Generated by Django 5.2 on 2025-06-13 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0007_mentorshiploop_created_at_mentorshiploop_purpose_and_more'),
        ('weeklycheckin', '0002_alter_weeklycheckin_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyCheckInMeetingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('weekly_goals', models.TextField(blank=True, null=True)),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('meetining_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship.mentorshiploop')),
            ],
        ),
    ]
