# Generated by Django 5.2 on 2025-06-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklycheckin', '0003_weeklycheckinmeetingschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklycheckinmeetingschedule',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
