# Generated by Django 5.2 on 2025-06-17 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchrequest', '0005_rename_weekly_goals_meetingschedule_purpose'),
        ('mentorship', '0007_mentorshiploop_created_at_mentorshiploop_purpose_and_more'),
        ('weeklycheckin', '0004_weeklycheckinmeetingschedule_google_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklycheckin',
            old_name='challenges',
            new_name='weekly_goals',
        ),
        migrations.AlterUniqueTogether(
            name='weeklycheckin',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='weeklycheckin',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklycheckin',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='weeklycheckin',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='matchrequest.matchrequest'),
        ),
        migrations.AddField(
            model_name='weeklycheckin',
            name='meetining_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklycheckin',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklycheckin',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklycheckin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='weeklycheckin',
            name='loop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentorship.mentorshiploop'),
        ),
        migrations.AlterField(
            model_name='weeklycheckin',
            name='week_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WeeklyCheckInFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('mentor_checked_in', models.BooleanField(default=False)),
                ('mentee_checked_in', models.BooleanField(default=False)),
                ('progress', models.TextField(blank=True, null=True)),
                ('challenges', models.TextField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('checkin_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship.mentorshiploop')),
            ],
            options={
                'unique_together': {('loop', 'week_number')},
            },
        ),
        migrations.DeleteModel(
            name='WeeklyCheckInMeetingSchedule',
        ),
        migrations.RemoveField(
            model_name='weeklycheckin',
            name='checkin_date',
        ),
        migrations.RemoveField(
            model_name='weeklycheckin',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='weeklycheckin',
            name='mentee_checked_in',
        ),
        migrations.RemoveField(
            model_name='weeklycheckin',
            name='mentor_checked_in',
        ),
        migrations.RemoveField(
            model_name='weeklycheckin',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='weeklycheckin',
            name='status',
        ),
    ]
