# Generated by Django 5.2 on 2025-06-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklycheckin', '0005_rename_challenges_weeklycheckin_weekly_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklycheckin',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
