# Generated by Django 5.2 on 2025-07-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklycheckin', '0006_weeklycheckin_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklycheckin',
            name='checkin_created',
            field=models.BooleanField(default=False),
        ),
    ]
